[project]
name = "blog-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "newsapi-python>=0.2.7",
    "requests>=2.32.5",
    "streamlit>=1.52.2",
]
